#include<iostream>

void fun() {
	std::cout<<"In Fun2"<<std::endl;
}

//error: ld returned 1 exit status
